FROM mcr.microsoft.com/dotnet/aspnet:9.0  AS base
COPY bin/Release/net9.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p e33ac6b2-5fd9-4346-a97e-f9b3dbb9a7ee

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "Acme.Bookshop.HttpApi.Host.dll"]